version: '3'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  finans-application:
    image: arunpk11/finans
    # network_mode: host
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - postgres 
    environment:
      RDS_HOSTNAME: postgres
      RDS_PORT: 5432
      RDS_DB_NAME: finans
      RDS_USERNAME: finansuser
      RDS_PASSWORD: User@123

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    # expose: "5432"
    network_mode: bridge 
    restart: always
    environment:
      POSTGRES_ROOT_USER: root
      POSTGRES_ROOT_PASSWORD: Admin@123 
      POSTGRES_USER: finansuser
      POSTGRES_PASSWORD: User@123
      POSTGRES_DB: finans
    volumes:
      - finans-data-volume:/var/lib/postgres/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Volumes
volumes:
    finans-data-volume: